### ISSUE TITLE
Build the supplier LIST service

### ISSUE THREAD

**Issue by harshwani1997** [20Fall-NYU-DevOps-Suppliers/suppliers#13]
As a user
I need to be able to get a list of all suppliers
So that I can list all suppliers

Assumptions:

- The LIST service will be part of the service.py file
- Create some test cases for this operation

Acceptance Criteria

When API call on routine 'GET suppliers/all'
Then I should get a list of suppliers with their id.

**Comment by rymaspic** [comment]
Is this the same story as the READ service?

**Comment by harshwani1997** [comment]
Hello. Going forward I assume they might have different functionalities, even the homework states it has two different functionalities! (Read a  particular resource/ List all the resources)
